export const staff = [
  {
    id: '1',
    userName: 'admin',
    email: 'jdoe@example.com',
    password: 'admin',
    roleId: 'Staff',
    counterId: 1,
  },
  {
    id: '2',
    userName: 'manager',
    email: 'asmith@example.com',
    password: 'manager',
    roleId: 'Manager',
    counterId: 2,
  },
  {
    id: '3',
    userName: 'mjones',
    email: 'mjones@example.com',
    password: 'securepassword3',
    roleId: 'Admin',
    counterId: 3,
  },
  {
    id: '4',
    userName: 'bclark',
    email: 'bclark@example.com',
    password: 'securepassword4',
    roleId: 'Staff',
    counterId: 4,
  },
  {
    id: '5',
    userName: 'ewilson',
    email: 'ewilson@example.com',
    password: 'securepassword5',
    roleId: 'Manager',
    counterId: 5,
  },
  {
    id: '6',
    userName: 'djohnson',
    email: 'djohnson@example.com',
    password: 'securepassword6',
    roleId: 'Admin',
    counterId: 6,
  },
  {
    id: '7',
    userName: 'kroberts',
    email: 'kroberts@example.com',
    password: 'securepassword7',
    roleId: 'Staff',
    counterId: 7,
  },
];
